### ISSUE TITLE
Tone down WordPress-Docs for wd_s

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/WDS-Coding-Standards#17]
We're using Sass Docs to deal with documenting our Sass...among other things which is causing wd_s to fail linting/Travis. 

Let's not be so strict!

**Comment by aubreypwd** [comment]
I'm fairly certain we need to include `WordPress-Docs`, but there's obviously a conflict with SASS, which I would assume PHPCS, ESLint, etc would not touch. Is this fixed by the addition of the SASS Linter @gregrickaby ?

**Comment by gregrickaby** [comment]
I despise `Wordpress-Docs`. It's endless false-positives for dumb things like:

`<?php echo wds_client_display_thing(); // WPCS XSS OK. ?>`

**ERROR: EXPECTED ONE SPACE BEFORE CLOSING PHP TAG**

**Comment by jrfoell** [comment]
@gregrickaby this line should be fine:

`<?php echo wds_client_thing(); // WPCS XSS OK. ?>`

I ran into variances with reporting vs. what @aubreypwd was seeing because we were running different phpcs and wpcs versions. Everyone using composer #14 should alleviate this and put us all on the same versions so we're seeing the exact same things.
