### ISSUE TITLE
Allow Class Files to be Named without class- Prefix

### ISSUE THREAD

**Issue by ggwicz** [WebDevStudios/WDS-Coding-Standards#64]
Currently, WDS Coding Standards require class file names to be named with a `class-` prefix.

So, let's say we have a file where we define the `Foo` class:

```
class Foo {
    public function bar() {
        return 'LOL';
    }
}
```

WDSCS wants this to be named `class-foo.php`, or else it will flag an error.

The thing is, we are already abandoning this file naming convention:
- We are using just the PascalCase class name + `.php` in a number of client projects already
- We are already using it in some internal projects too, like OOPS-WP

So the above class would be named `Foo.php`

I would vote that this is convention is clearer and cleaner, and that the `class-` prefix is no longer that helpful now:
- This convention comes from WordPress coding standards, and is still used there and in e.g. WooCommerce.
- But these conventions come from a time when PHP namespacing couldn't be used.
- So class prefixes and this class file naming convention helped organize things a bit. For example, the `WP_Error` class being named `WP_Error` and having the file name `class-wp-error.php`

Makes sense for them, but I'd argue these conventions no longer make sense for us.

**Comment by jmichaelward** [comment]
+1000000000000000

**Comment by phatsk** [comment]
+1000000000000000

**Comment by aubreypwd** [comment]
My thoughts:

- On principle, I think all code should follow/adhere to WordPress's own Coding Standards as a base, this would be a deviation from that, though minor
- If there is no way to configure PSR4 autoloading to prefix/use the WordPress CS names e.g. `class-my-class.php`, then I say go for it because we don't have an option otherwise
- But if there is a way, I'd like to see us explore it more to keep in-sync with WPCS

**Comment by jmichaelward** [comment]
PSR-4 and WordPress's preferred methods of naming class names are incompatible, which states that the leading namespace name must match the starting root of the directory structure, subnamespaces must match the directory structure, and the terminating class name must match the name of the file.

See: https://www.php-fig.org/psr/psr-4/

We didn't discuss it enough during last Thursday's meeting, but WordPress Coding Standards are completely in flux right now themselves because of the shift to the minimum PHP requirement. Namespaces didn't even exist in PHP 5.2. See: https://make.wordpress.org/core/2019/03/26/coding-standards-updates-for-php-5-6/

**Comment by jmichaelward** [comment]
Also, perhaps internally, could we discuss the rationale for why all code should follow or adhere to WPCS? If that's the case, why does WDCS exist at all?

I agree with Mika's sentiment here: https://make.wordpress.org/core/2019/03/26/coding-standards-updates-for-php-5-6/#comment-35626

**Comment by ggwicz** [comment]
There's certainly an interesting discussion to be had here about alignment with with WPCS generally.

While I do genuinely agree with trying to align with WPCS as much as possible,I think using "modern" PHP _at all_ will always entail **some** deviation from WPCS.

And I personally think this is okay—our goals are different than WP Core's goals, so our coding standards can be different than their coding standards (in as few places as possible ideally, but still).

I submitted a quick implementation of this change ahead of our BEE scrum today. That's visible in a PR here → https://github.com/WebDevStudios/WDS-Coding-Standards/pull/65

**Comment by phatsk** [comment]
I'm in agreement that deviating from WPCS is OK when it makes sense for us. I think that the way we're moving towards using namespaces, libraries, etc, lends towards abandoning the "WordPress" way of writing class names and class file names in general.

I think taking advantage of PSR4 for autoloading is a much better approach to handling the growing OOP style we're using, as opposed to having to register our own autoloader on every project we create. Even when we have a boilerplate autoloader, we inevitably run into issues with loading, and it's a chunk in our main plugin file that could be reduced down to `require path/to/autoload.php`. I know it's just moving the mystery box from one file to another (or several), but in general once a project is setup to use PSR4 we shouldn't have to touch anything in the autoloader.

Another point to this - namespaces give us much more control over structure, whereas the WordPress standard was introduced when namespaces weren't a thing. Having `WP_Post` or `WP_Query` in files like `class-wp-post.php` made sense because otherwise it was hard to distinguish what came from where. With namespaces, things like `WP\Post` or `WP\Query` become viable, and the directory structure informs the code path instead of a disconnect where someone has to say "Oh, that's a class, so I need to hope I can find the right file to correspond with this classname". Instead, we know where a namespace's root is and everything from there is following folders until we get to the desired file.

**Comment by aubreypwd** [comment]
Adding notes to this I think the consensus is to do this only on directories that are using PSR4 autoloading e.g. in `composer.json`.

**Comment by aubreypwd** [comment]
With a custom sniff we can:

`Current file > cd .. > cd .. > cd .. > (until we find composer.json) > read composer.json > is using PSR4? > yes | no > act appropriately on current file`

And I think we could _also_ check (as you've suggested) if the composer.json is in a `src/` folder as well!

**Comment by ggwicz** [comment]
Might be nitpicking, but I'd vote against looking at composer.json _within_ `src/` — it's often not in that directory.

The "anything in a `src/` dir" sniff _seems_ easy to implement to me—is that so?

If so, I'd vote to have that sniff and then maybe _also_ a `composer.json`-based sniff if time allows etc.

Thoughts?

**Comment by aubreypwd** [comment]
Work and discussion on this will continue https://github.com/WebDevStudios/php-coding-standards/issues/12
